dictdiffer/__init__.py, tests/test_dictdiffer.py
* Fixes exception when dict has unicode keys and ignore parameter is provided.  (closes #50)
=> diff: fix for unicode keys

AUTHORS, dictdiffer/__init__.py, dictdiffer/_compat.py, dictdiffer/conflict.py, dictdiffer/merge.py, dictdiffer/resolve.py, dictdiffer/unify.py, dictdiffer/utils.py, dictdiffer/version.py, tests/test_conflict.py, tests/test_dictdiffer.py, tests/test_merge.py, tests/test_resolve.py, tests/test_unify.py, tests/test_utils.py
As discussed with @jirikuncar a while ago, here the pull request of a more pragmatic dictdiffer.merge implementation.
Dictdiffer v0.5.0: merging
* Alters the dictdiffer.diff function to allow expanding patches and to utilize a path_limit parameter, which stops the extraction process at a given point
* Adds the following files to handle the merging process:
* merge.py
* conflict.py
* resolve.py
* unify.py
Which is executed in the following steps:
* The differences between a latest common ancestor (lca) and two other data structures are extracted
* The two occuring differences lists are checked for conflicts
* Those conficts are resolved
* The patches are unified
Signed-off-by: Martin Vesper <martin.vesper@cern.ch>
=> dictdiffer: pragmatic merge

AUTHORS, dictdiffer/__init__.py, dictdiffer/_compat.py, dictdiffer/utils.py, docs/index.rst, tests/test_dictdiffer.py
This patch allows to deal with a tolerance when comparing 2 numerical values.
Currently, only int, long (for PY2) and float types use this new parameter.
=> diff: add tolerance parameter

.travis.yml, dictdiffer/version.py, setup.cfg, setup.py
* Adds support for Python 3.5 and wheels.
* Adds deploy section for automatic PyPI releases.  (closes #64)
=> global: support for Python 3.5 and wheels

dictdiffer/__init__.py, dictdiffer/_compat.py, tests/test_dictdiffer.py
* NEW Adds support for comparing mutable mappings, sequences and sets
from `collections.abs` module.  (closes #67)
=> diff: support for collection.abc subclasses

dictdiffer/conflict.py, dictdiffer/unify.py, tests/test_conflict.py, tests/test_merge.py
* Fixes the way patches are chosen to be part of the final result.
* Adds regression tests for the added fix.
Signed-off-by: Mihai Bivol <miha.bivol@cern.ch>
=> unify: unified_patches order fix

dictdiffer/__init__.py, setup.py, tests/test_dictdiffer.py
* NEW Adds support for comparing NumPy arrays.  (closes #68)
=> diff: initial Numpy support

dictdiffer/__init__.py, docs/conf.py, docs/index.rst, pytest.ini, run-tests.sh, setup.py
* Improves API documentation for `ignore` argument in `diff` function.
(addresses #79)
* Executes doctests during PyTest invocation.
=> docs: diff argument clarification

dictdiffer/__init__.py, tests/test_dictdiffer.py
* FIX Changes order of items for REMOVE section of generated patches
when `swap` is called so the list items are removed from the end.
(closes #85)
=> swap: reversed order of REMOVE items

dictdiffer/__init__.py, tests/test_dictdiffer.py
* INCOMPATIBLE Fixes problem with diff results that reference the
original structure by introduction of `deepcopy` for all possibly
unhashable items. Thus the diff does not change later when the
diffed structures change.
cc @mikaelho
=> diff: deep copy of unhashable types

.travis.yml, AUTHORS, setup.py, tox.ini
* Adds Python 3.6 to test matrix.
--
@tiborsimko can you please remove the LGTM status check and maybe enable review?
=> global: removal of support for Python 2.6

dictdiffer/__init__.py, tests/test_dictdiffer.py
Found a bug where if a sub key is unicode then we get an exception.
Added test case example.
=> fix unicode sub key bug

CHANGES, RELEASE-NOTES.rst, dictdiffer/version.py
addresses https://github.com/inveniosoftware/dictdiffer/issues/101#issuecomment-386110010
=> release: v0.7.1

dictdiffer/_compat.py
Python porting best practice [use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection) to save an import and pass both PyLint and Flake8 tests with neither 'pragma' nor 'noqa'.
=> Use feature detection not version detection in _compat.py

dictdiffer/__init__.py, dictdiffer/_compat.py, setup.py, tests/test_dictdiffer.py
PR for this issue: [Ignore does not work with integers #112](https://github.com/inveniosoftware/dictdiffer/issues/112)
```
(py3_dictdiffer) ➜  dictdiffer git:(master) ./run-tests.sh
Skipped 1 files
lists of files in version control and sdist match
running pytest
running egg_info
writing dictdiffer.egg-info/PKG-INFO
writing dependency_links to dictdiffer.egg-info/dependency_links.txt
writing requirements to dictdiffer.egg-info/requires.txt
writing top-level names to dictdiffer.egg-info/top_level.txt
reading manifest file 'dictdiffer.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dictdiffer.egg-info/SOURCES.txt'
running build_ext
======================================================================= test session starts …
```
=> Ignore does not work with integers #112

dictdiffer/utils.py, tests/test_dictdiffer.py
* BETTER Two NaN values are considered the same, hence they are not
shown in `diff` output.  (closes #114)
--
cc @t-b
=> diff: support diff of numpy NaN and float('NaN')

dictdiffer/__init__.py, tests/test_dictdiffer.py
I need to do further processing on the returned diff, so having to handle both dot and list notations is a hassle.
**Example**
```
(   ('change', ['db_suburb', 'title', 'args', 0, 'args', 0], (60, 601)),
(   'change',
['db_suburb', 'title', 'args', 0, 'sql'],
('VARCHAR(60)', 'VARCHAR(601)')),
(   'change',
'db_suburb.title.sql',
('VARCHAR(60) NOT NULL', 'VARCHAR(601) NOT NULL')))
```
Trying to extract the 3 occurences `db_suburb` in the above diff is a pain.
```
changes = (   ('change', ['db_suburb', 'title', 'args', 0, 'args', 0], (60, 601)),
(   'change',
['db_suburb', 'title', 'args', 0, 'sql'],
('VARCHAR(60)', 'VARCHAR(601)')),
(   'change',
['db_suburb', 'title', 'sql'],
('VARCHAR(60) NOT NULL', 'VARCHAR(601) NOT NULL')))
```
Whereas above can be done so quite easily with:
``` …
```
=> diff: argument for toggling dot notation

dictdiffer/__init__.py, dictdiffer/utils.py, tests/test_dictdiffer.py
Resolve issue #107.
Use a custom type `DottedIgnoreKey` to deactivate interpretation (interpolation) of keys (with dot inside).
Add unit-tests to check the correctness/fix.
=> Wrong diff in case of dictionary has dotted keys in ignore in dictdiffer.

tests/test_dictdiffer.py
This adds a couple unit tests to verify the functionality of comparing sets. This is related to @jirikuncar and myself's conversation in https://github.com/inveniosoftware/dictdiffer/issues/131#issuecomment-564341344.
`test_add_set_shift_order` - FAILS as is. This should pass given we're comparing two unordered, unindexed sets. The only reported diff should be an ADD. I've confirmed that #133 fixes this issue.
`test_change_set_order` - Functions correctly
Thanks @jirikuncar !
=> Add failing unit test for diffing sets

dictdiffer/__init__.py, tests/test_dictdiffer.py
* Adds missing return statement to avoid yielding CHANGE for sets.
(addresses #131)
=> diff: fix comparison of sets

dictdiffer/__init__.py
This removes the dependency on setuptools on runtime.
=> Simplify determining if numpy is available

dictdiffer/__init__.py, dictdiffer/utils.py, dictdiffer/version.py, tests/test_dictdiffer.py
Hi
I encountered an issue using this nice package: when I want to compare floats, I sometimes need absolute tolerance because of very small values. For example, I don't really care about 100% difference between `1e-16` and `2e-16`, while I do care of a 1% difference between `1` and `1.01`. This case could be solved using a tolerance of `0.01` and an absolute tolerance of `1e-15`.
This PR adds this feature with a few test cases that show more examples.
=> diff: add support for absolute tolerance of floats

dictdiffer/merge.py, tests/test_merge.py
My use-case requires the `ignore` param when diffing dictionaries.
I started using `Merger` today, and found this option was missing in that class.
=> merge: support ignore param to diff function
